### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by msabramo** [47ng/next-usequerystate#237]
I did:

```
npm install next-usequerystate
```

and then added to my code:

```js
import { useQueryState } from 'next-usequerystate'
```

I got this error:

## Failed to compile
```
./node_modules/next-usequerystate/dist/esm/index.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export * from './defs';
| export * from './useQueryState';
| export * from './useQueryStates'
```

![Screen Shot 2021-08-04 at 1 13 06 PM](https://user-images.githubusercontent.com/305268/128248621-04bc2c54-0d42-4c3e-b4aa-456b1dd616a3.png)

**Comment by franky47** [comment]
Could you tell me more about your setup (transpiler, bundler, general processing of source files into final artifacts, use of ES modules, TypeScript, Babel, etc..) ?

**Comment by msabramo** [comment]
This happens with an app create with `use-next-app`,  using the `next-learn-starter`:

```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"
```

**Comment by msabramo** [comment]
It's not specific to `next-learn-starter`. I was able to reproduce it with an app created by:

```
npx create-next-app nextapp --use-npm
```

**Comment by msabramo** [comment]
I didn't think it would matter, but for the sake of completeness, it also still happens without the `--use-npm` flag:

```
npx create-next-app nextapp
```

**Comment by msabramo** [comment]
```
$ npm list next
nextapp@0.1.0 /private/tmp/nextapp
├─┬ eslint-config-next@11.0.1
│ └── next@11.0.1 deduped
├─┬ next-usequerystate@1.3.0
│ └── next@11.0.1 deduped
└── next@11.0.1
```

**Comment by msabramo** [comment]
This config seems to be using webpack5, in case that matters. I saw this when running `npm run dev`:

```
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
```

**Comment by msabramo** [comment]
Ah, interesting. I followed the [link in the above message](https://nextjs.org/docs/messages/webpack5) about webpack5 and that lead me to try putting:

```js
webpack5: false
```

in `next.config.js` and then it seemed to work!

Note however that this is not a long-term solution as the above link says:

> In Next.js 11 webpack 5 was enabled by default for all applications. You can still opt-out and use webpack 4 to help with backwards compatibility using webpack5: false in next.config.js
In the next major version webpack 4 support will be removed.

**Comment by msabramo** [comment]
Possibly of interest?

https://github.com/webpack/webpack/issues/12598

**Comment by msabramo** [comment]
#238 seems like it might fix this. Hopefully it doesn't have any bad side-effects.

**Comment by bogdansoare** [comment]
any news on this?

**Comment by franky47** [comment]
@msabramo & @bogdansoare, let me know if 1.4.0-beta.5 works for you. I'm still waiting on a TS types bugfix from Next.js to bump a security PR and I'll look into crafting a proper release.

**Comment by msabramo** [comment]
Yep I'm using 1.4.0-beta.5 and it's working well for me.

```
$ npm list next-usequerystate
next-stock-prototype@0.1.0 /Users/abramowi/dev/adobe/sensei/next-stock-prototype
└── next-usequerystate@1.4.0-beta.5
```

Thank you!
