### ISSUE TITLE
Demo Code not working

### ISSUE THREAD

**Issue by surjithctly** [47ng/next-usequerystate#276]
I set up a bare-bone next js project from scratch and added the demo code. But it doesn't work. It throws error with latest Next versions. 

See Live: https://stackblitz.com/edit/nextjs-vhieqw?file=pages%2Findex.js

Error

```
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by franky47** [comment]
Can you try the latest beta ? I think it got solved there, if it's confirmed I can ship an official release.

**Comment by surjithctly** [comment]
Yup. It's working in the beta.

**Comment by franky47** [comment]
Version 1.4.0 has been released with an ESM/CJS dual build which fixes this issue.
