### ISSUE TITLE
Documentation for `useQueryStates`

### ISSUE THREAD

**Issue by surjithctly** [47ng/next-usequerystate#277]
From the code, I can see that you provide `useQueryStates` for multiple state updates. Is this functional? It's never mentioned in the docs.  I tried the following but doesn't seem to be working. 

```
  const [query, setQuery] = useQueryStates({
    foo: "foo",
    arr: "arr"
  });
```

**Comment by franky47** [comment]
This may be YAGNI, my use-case at the time was that I wanted to synchronise setState for multiple query parameters, and have the router guarantee to be updated in a single tick/render cycle.

But it turns out this was a bad design idea in the first place (the URL can change independently of the app's desires), hence why the feature is not documented, it might be removed in the next version.

Is this something you'd find useful? If so, could you run me through your use-case ?

**Comment by franky47** [comment]
As a side-note, the way I'd enforce constraints on various properties to be stored in the URL would be to collect them in an object, and store that in JSON under a single query key:

```ts
const [{ foo, bar }, setQueryState] = useQueryState('key', {
  serialize: obj => encodeURIComponent(JSON.stringify(obj)),
  parse: query => JSON.parse(decodeURIComponent(query)) as { foo: string; bar: number }
})
```

With type-safey and runtime-safety provided by [`zod`](https://github.com/colinhacks/zod):
```ts
import { z } from 'zod'

const schema = z.object({
  foo: z.string(),
  bar: z.number()
})

const [{ foo, bar }, setQueryState] = useQueryState('key', {
  serialize: obj => encodeURIComponent(JSON.stringify(obj)),
  parse: query => schema.parse(JSON.parse(decodeURIComponent(query)))
})
```

**Comment by surjithctly** [comment]
My use case is to update multiple state at once. Eg: If I have a form submission with 3 items, I want to update all same time. 
Eg: `item1=value&item2=value&item3=value`

By the way, if the above solution work, that would be fine, but your first code throws `TypeError: Cannot read property 'foo' of null` Error.

**Comment by franky47** [comment]
Ah yes I forgot to account for the case where the query key is not present:

```ts
const [query, setQueryState] = useQueryState('key', {
  serialize: obj => encodeURIComponent(JSON.stringify(obj)),
  parse: query => JSON.parse(decodeURIComponent(query)) as { foo: string; bar: number }
})

const { foo, bar } = query ?? {
  foo: 'default value for foo',
  bar: 42
})
```

**Comment by surjithctly** [comment]
Works, but it seems the URL is now looking something like this:  `?key=%257B%2522foo%2522%253A%2522foo%2522%252C%2522bar%2522%253A%2522bar%2522%257D`

Is this expected?  I was looking for something like `item1=value&item2=value&item3=value`

**Comment by franky47** [comment]
Yes it's the encodeURIComponent output of a JSON object. If you want the URL you describe, you'll have to go for individual useQueryState per entry.

**Comment by surjithctly** [comment]
Understood! I'll keep using the individual. 

Thanks, man! Waiting for the latest version to publish. ✌️

**Comment by surjithctly** [comment]
Okay, I tried updating multiple one by one, It only adds one item in the URL, not all. See the minimal reproduction here: https://stackblitz.com/edit/nextjs-t4adky?file=pages%2Findex.js

Code I used :

```js
  const handleSubmit = (data) => {
    setName('Johan');
    setEmail('jo@gmail.com');
    setPhone('123456');
  };

  // return func
  <button onClick={() => handleSubmit()}>Update values</button>
```

**Comment by franky47** [comment]
Hey @surjithctly, thanks for the report, I finally managed to take a look at your case.

The gist of it is: a call to setXYZ will do a route update, which is an async operation and will take time to apply the new querystring to `window.location.search`. This same `window.location.search` is used as the base to append query updates in the subsequent hooks, so in order for sequential updates to succeed, they need to be awaited.

I've pushed a fix that simply returns the internal call to `router.push/replace`, so it can be awaited:
```ts
const handleSubmit = async (data) => {
  await setName('Johan')
  await setEmail('jo@gmail.com')
  await setPhone('123456')
}
```

Unfortunately, doing it all in parallel won't work, for the same reason as stated above:
```ts
const handleSubmit = async (data) => {
  // This won't work:
  await Promise.all([
    setName('Johan'),
    setEmail('jo@gmail.com'),
    setPhone('123456')
  ])
)
```

I'll run some more tests and publish a release today.

**Comment by franky47** [comment]
You can check out `1.4.0`, it has the API of the example above. I'll investigate the state (pun intended) of useQueryStates, as this is definitely something that I'd like to have, since Next.js does a full page render on **any** query update (might as well batch them).

**Comment by surjithctly** [comment]
Thank you. I tried this. Now it adds up without replacing. But one by one after a delay. 

I was doing a backend call on button change and I need all the values to be updated in the state, but its taking so much time updating 4-8 items.  My current workaround was calling the `router.push` manually without the `pathname`

```
    router.push({
      query: {
        name: data.name,
        email: data.email,
        phone: data.phone
      }
    });
```

The above updates the URL relatively fast, but does it together.

**Comment by franky47** [comment]
I've published `1.6.0-beta.1` which includes a proper implementation for `useQueryStates`. Check out the [Documentation](https://github.com/47ng/next-usequerystate#multiple-queries), and let me know if you have any comments, issues or suggestions.

Thanks!

**Comment by surjithctly** [comment]
I just tried your demo code . It throws `TypeError: parse is not a function`

I tried without the `queryTypes`. Is that mandatory? 

```js
  const [name, setName] = useQueryStates(
    {
      first: "john",
      last: "doe"
    }
  );

  const { first, last } = name;

  await setName({
      first: "joe",
      last: "cooper"
    });
```

**Comment by franky47** [comment]
Yes, you need to tell it what type of key is used. To provide a default value, you can do this:
```ts
const [{ first, last }, setName] = useQueryStates({
  first: queryTypes.string.withDefault('john'),
  last: queryTypes.string.withDefault('doe')
})
```

I'll try and make the documentation a bit more clear, thanks for your feedback!

**Comment by surjithctly** [comment]
Possible to make string as fallback if nothing provided. So instead of throwing error, it can fallback to string?

**Comment by franky47** [comment]
That's what is done in `useQueryState`, and it took me 4 days and 5 TypeScript function overloads to type this behaviour correctly.

I'm not planning on bringing it to `useQueryStates`, but if you want to open a PR I'll be happy to review it.

**Comment by surjithctly** [comment]
Hmm.. then I guess one-line of ` queryTypes.string.withDefault('john')` doesn't make any harm! 

Will keep using that. I didn't touch typescript myself.

**Comment by franky47** [comment]
`useQueryStates` is now available in version 1.6.0.

**Comment by msabramo** [comment]
Hi @franky47:

I saw that early in the thread you said:

> it turns out this was a bad design idea in the first place (the URL can change independently of the app's desires), hence why the feature is not documented, it might be removed in the next version.

but then you updated `useQueryStates` in version 1.6.0.

Should users of the package take this to mean that you now consider it supported and it probably won't be removed?

Thanks!

**Comment by franky47** [comment]
The remark was on the way to handle default values (which applies both to `useQueryState` and `useQueryStates`).

What is implemented is as follows:
- The URL is the source of truth
- When there is no valid value in the URL (none at all or does not pass parsing), the default value is returned as the state value
- Clearing the query string in the URL can be done by setting the state to `null`, which in turn will return the default value in the state value
