### ISSUE TITLE
array serializer filters out `0` if item serializer is integer

### ISSUE THREAD

**Issue by el-ranye** [47ng/next-usequerystate#294]
This `Boolean` filter is filtering out `0` from the list. It should probably only filter out `null` and `undefined` values:

https://github.com/47ng/next-usequerystate/blob/next/src/defs.ts#L200

**Comment by franky47** [comment]
Zero is a falsy value in JavaScript, and I would expect it to parse to a `false` value, so this is expected.
- 0 -> false
- 1 -> true

Also relevant values that should map to `false`:
- `''` (empty string)
- `NaN`
- `null`
- `undefined`
