### ISSUE TITLE
withDefault([]) adds an empty query string to url

### ISSUE THREAD

**Issue by prasannamestha** [47ng/next-usequerystate#332]
Hello,

If we use `useQueryStates()` containing one or more arrays,  setting a value using empty array adds an empty query string in url.

To reproduce:
```
const [filters, setFilters] = useQueryStates({
    gender: queryTypes.string,
    tags: queryTypes.array(queryTypes.string).withDefault([]),
  });

const { gender, tags } = filters;

// Now set just the gender
setFilters((oldState) => ({
      ...oldState,
      gender: 'male',
}));
```

The above code adds this to url: `?tags=&gender=male`

Created this PR to fix the issue: https://github.com/47ng/next-usequerystate/pull/331

Thanks

**Comment by franky47** [comment]
I may be nitpicking, but I'd say this is expected.

If you think of the equivalent with a string query, setting it to an empty value (an empty string) will give you the same "empty value, but key in the querystring" result. Setting the value to `null` will remove the key entirely.

There may be a difference of meaning between "no value at all" (no key in the query, `null` state returned by the hook) and an empty value (empty string/array), but that's application-specific.

I agree that it gets even more confusing when using default values, as setting the state to either `null` to clear the query key or to the default value (which keeps the query key) result in the same state value being returned by the hook.

**Comment by prasannamestha** [comment]
Yeah. I noticed this issue when I explicitly set the array value as `null` and then set the gender, it was resetting the tags value back as an empty array. 


```
// User clears the tags first
setFilters((old) => ({
  ...old,
  tags: null
})

// This works fine and the url is cleared


// Then user sets the gender
setFilters((old) => ({
  ...old,
  gender: 'male'
})

// Here the tags value has been changed from null to an empty array
```

I understand your point, but I don't see a benefit in holding the empty state of an array in the url. Could it be that I am missing some use case?

**Comment by franky47** [comment]
> it gets even more confusing

Indeed and that's what's happening here (it took me a while too): when using a default value, it's returned instead of `null` when the querystring is missing the associated key. By setting the state with a spread like this, the default is applied for the `tags` key and therefore the URL is updated to show an empty key.

For `useQueryStates`, you can use partials to only update a subset of the keys, without touching the others:
```ts
// User clears the tags first
setFilters({
  tags: null
})

// Then user sets the gender
setFilters({
  gender: 'male'
})
```

**Comment by prasannamestha** [comment]
>you can use partials to only update a subset of the keys, without touching the others

This is exactly what I needed. Thanks!

**Comment by franky47** [comment]
Closing this issue and related PR #331 as a solution for the initial problem was found.
