### ISSUE TITLE
NextRouter was not mounted

### ISSUE THREAD

**Issue by PranavRayudu** [47ng/next-usequerystate#346]
I am getting an `Unhandled Runtime Error
Error: NextRouter was not mounted.` when using `useQueryState` with Next.js 13.4.12

Seems like according to [this page](https://nextjs.org/docs/messages/next-router-not-mounted) Nextjs router instantiation should import from `next/navigation` instead of `next/router` for client components.

**Comment by franky47** [comment]
Could you try the 1.8.0-beta.6 version and use `from "next-usequerystate/app"` as the import please?

See #343.

**Comment by PranavRayudu** [comment]
Ah, that seemed to work, thanks!

**Comment by franky47** [comment]
Let me know if you encounter some issues, I'm planning to release this soon.
