### ISSUE TITLE
Next.js 13 shallow routing alternative

### ISSUE THREAD

**Issue by BenMcD0nald** [47ng/next-usequerystate#361]
Hey,

I saw this come up on the discussion for next.js shallow routing and have been trying to work out if it could serve as a temporary replacement. I'm aware use cases are different and for some things this will work fine but I'm having difficulty working out if it could handle what I'm trying to do and I'm just not implementing it correctly etc.

Essentially I have a server rendered page which fetches initial 'post' information based on the URL query. It then passes this through to an infinite scroll component that a) fetches/adds a new page of posts when the user scrolls down and b) updates the page depending on which is most visible.

The update of the page is working just fine and I can see from your examples how to pull this on the initial page load so I can do something like `const page = pageParser.parseServerSide(searchParams.page) || parseInt(searchParams?.page) || 1`

However, each time the infinite scroll adds a new page and rerenders all changes to the URL are lost and it reverts to the page number from initial load. 

I've tried a number of other attempts to work around the shallow routing issue and all seem to fail for similar reasons. My initial thoughts are that this isn't working because next/router doesn't acknowledge the changes properly and therefore when the infinite scroll component rerenders it's causing these changes to be lost. 

Are you able to provide any feedback and confirm if this shouldn't be the case and it's likely down to my implementation or if my assumptions are correct and your package doesnt really accommodate for this sort of use case?

Thanks

**Comment by franky47** [comment]
> However, each time the infinite scroll adds a new page and rerenders all changes to the URL are lost and it reverts to the page number from initial load.

I would say your issue comes from the infinite scroll having a side-effect that changes the URL.

If you see the infinite scroll as a pagination mechanism, then it should update the querystring accordingly when injecting new content, so that a refresh of the page lands you in the same place in the feed.

**Comment by BenMcD0nald** [comment]
Currently it actually adds pages out of view so there's no URL update attached to that. I'm using intersection observers to update the URL based on what page is most visible however that's not running when pages are added. 

The paging mechanism is working fine on that basis. If I **refresh** the page I land back on the expected page, it's just that it reverts back to this page number in the URL each and every time a new 'page component' is added under the existing ones (again the setPage() function not running here) despite me updating it when the intersection observer triggers. 

Still, it's interesting that you don't think this should be expected behaviour. I'll do some further digging to see if I can either work out where the issue is and if not maybe put a codepen together. In an ideal work the next developers will get their act together soon and sort proper shallow routing but I'm not holding my breath on that one.

Thanks for your time

**Comment by franky47** [comment]
> I'll do some further digging to see if I can either work out where the issue is and if not maybe put a codepen together.

That would be great, thanks!

> it's just that it reverts back to this page number in the URL each and every time a new 'page component' is added under the existing ones (again the setPage() function not running here) despite me updating it when the intersection observer triggers.

What causes this revert?

**Comment by BenMcD0nald** [comment]
Hey,

So I still have a few things to figure out when it comes to my specific project but wanted to let you know that I think I found what the issue is when it comes to the URL reverting.

I was using a server action for the data fetching function, so it was actually this being called that was causing the URL to get reset. Running this on the client appears to work just fine. Not 100% sure there's a workaround that will let me keep this function on the server prior to them implementing shallow routing properly but I think there's a possible way through to get my app working using your package for now.

Appreciate the help and the time you put into creating the package/flagging it on the discussion!

**Comment by franky47** [comment]
Thanks for the feedback!

> I was using a server action for the data fetching function, so it was actually this being called that was causing the URL to get reset. 

That's very intriguing.. I haven't played much with server actions yet, I'll have to run some tests to reproduce this behaviour.
