### ISSUE TITLE
shallow: false, doesn't always trigger server to re-render (RSC local cache)

### ISSUE THREAD

**Issue by OlegLustenko** [47ng/next-usequerystate#367]
When I'm clicking in a fast manner on different URL states, the server does not receive a new URL 

link to reproduce: 
https://stackblitz.com/edit/stackblitz-starters-u6p1rn?description=The%20React%20framework%20for%20production&file=app%2Fpage.tsx,app%2Fglobals.css,tailwind.config.ts,app%2F_tabs.tsx,app%2F_filters.tsx,app%2Flayout.tsx&title=Next.js%20Starter

loom:
https://www.loom.com/share/2669f4dc7c6b4188b81fb81b4874f9d3

**Comment by franky47** [comment]
Thanks a lot for the detailed report, I was able to reproduce on my end too.

I believe what happens, if you look at the network tab in devtools, is that there are no calls to the `_rsc` endpoints for the page when the query changes **after** you've passed all options / combinations.

That's the Server Component cache seeing an URL it already had processed before, and returning the data as it was rendered from the local cache on the client, without hitting the server.

Adding a call to `router.refresh()` after updating the URL seems to solve this issue. However, doing that for every non-shallow update may be wasteful if the server-side render is pure (no side-effects like logging page views). If for example you wish to fetch fresh data on the backend based on query params, you can opt-in to bypass the local RSC cache after the query has updated the URL:

```ts
const router = useRouter()

const setUrlTabNotShallow = (value: string) => {
  setUrlTab(value, { shallow: false, history: 'push' }).then(() => router.refresh())
}
```

**Comment by franky47** [comment]
Closing as there is a workaround.

PRs welcome to add this as an option extending the `shallow` boolean option.
