### ISSUE TITLE
Cannot find module "next/navigation"

### ISSUE THREAD

**Issue by mateogianolio** [47ng/next-usequerystate#368]
Hey!

I'm having issues with the `next/navigation` import inside defs.ts. I can see that it was patched [here](https://github.com/47ng/next-usequerystate/blob/next/packages/next-usequerystate/src/useQueryState.ts#L1) so I assume [`defs.ts`](https://github.com/47ng/next-usequerystate/blob/next/packages/next-usequerystate/src/defs.ts#L1) should be changed as well? :)

Here is the diff that temporarily solved my problem:

```diff
diff --git a/node_modules/next-usequerystate/dist/index.js b/node_modules/next-usequerystate/dist/index.js
index c15d5de..f59d8e8 100644
--- a/node_modules/next-usequerystate/dist/index.js
+++ b/node_modules/next-usequerystate/dist/index.js
@@ -94,7 +94,7 @@ import { useRouter as useRouter2, useSearchParams } from "next/navigation.js";
 import React from "react";
 
 // src/defs.ts
-import "next/navigation";
+import "next/navigation.js";
 
 // src/update-queue.ts
 var FLUSH_RATE_LIMIT_MS = 50;
```

**Comment by franky47** [comment]
Ah, thanks! Would you like to open a PR?
