### ISSUE TITLE
Default value with parseServerSide not showing

### ISSUE THREAD

**Issue by ru-van-urk** [47ng/next-usequerystate#384]
When using the parser in a server component the default does not seem to be working. A reproduction can be found here:

https://codesandbox.io/p/sandbox/github/ru-van-urk/next-usequerystate-server-default-bug?file=/src/app/page.tsx:1,1

I have made both a client and a server example. The client example works as expected but the server one does not.

``` 
    const string = parseAsString
    .withDefault("this is a string")
    .parseServerSide(searchParams.string);
```

In this example the default never gets set and string will always be undefined even though typescript marks it as defined.

I am wondering now if this is intentional or a bug.

**Comment by franky47** [comment]
Thanks for the reproduction! This is indeed a bug.

Parsers expect a string as their input type, so if the query is undefined on the server, it is currently defaulting to an empty string, which is not nullish, so the correct default value is not applied.

I'll try to push a release with a fix this afternoon. In the mean time, you should be able to use this  workaround:

```ts
const string = parseAsString
  .withDefault("this is a string")
  .parseServerSide(searchParams.string ?? "this is a string");
```
