### ISSUE TITLE
Typo in the latest changelog

### ISSUE THREAD

**Issue by snelsi** [47ng/next-usequerystate#396]
In the latest [v1.12.0 Github changelog](https://github.com/47ng/next-usequerystate/releases/tag/v1.12.0):

> This feature restores compatibility with Next.js `12.0.3-canary.6` and higher

I think it's a typo, it should be `14.0.3-canary.6`.

**Comment by franky47** [comment]
Thanks, it's fixed. Also added a note that there is no need for the experimental flag when using `next@14.0.3-canary.8` and above.
