### ISSUE TITLE
useQueryState with push mode is not updated after browser back

### ISSUE THREAD

**Issue by gkielwasser** [47ng/next-usequerystate#418]
## Context

What's your version of `next-usequerystate`?
1.13.0

Next version: 14.0.3

Are you using:

- ❌ The app router
- ✅ The pages router

## Description

I'm using useQueryState  with the history push mode. I would expect using browser back button would update query state. It seems back is not taken in account and therefore the state is not updated.

## Reproduction

[CodeSandbox](https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-7dhhdx?file=%2Fpackage.json%3A11%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp4h1xis0009356ie24ynd5o%2522%252C%2522sizes%2522%253A%255B65.92550993922475%252C34.07449006077525%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp4h1xir0003356i48n0mski%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp4h1xir0006356iveqjoy8o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp4h1xis0008356il6il8ph0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp4h1xir0003356i48n0mski%2522%253A%257B%2522id%2522%253A%2522clp4h1xir0003356i48n0mski%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp4h1xir0002356i9u3cdwda%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252F_app.tsx%2522%252C%2522id%2522%253A%2522clp4h4ntb00be356i9z7oy19h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FLocaleSwitcher.tsx%2522%252C%2522id%2522%253A%2522clp4heb4z01nc356il21vj4yh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fmessages%252Fde.json%2522%252C%2522id%2522%253A%2522clp4hq32f02sm356ifukhtjb3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fmessages%252Fen.json%2522%252C%2522id%2522%253A%2522clp4htjek0382356i0847bkcv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clpllgnm70002356ht763p5en%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpllgnm70002356ht763p5en%2522%257D%252C%2522clp4h1xis0008356il6il8ph0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp4h1xis0007356it272sa3i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522clp4h1xis0008356il6il8ph0%2522%252C%2522activeTabId%2522%253A%2522clp4h1xis0007356it272sa3i%2522%257D%252C%2522clp4h1xir0006356iveqjoy8o%2522%253A%257B%2522id%2522%253A%2522clp4h1xir0006356iveqjoy8o%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp4h1xir0004356i1o405bv6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp4h1xir0004356i1o405bv6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I'm not sure it can be well reproduced in CodeSandbox. 

Example: Steps to reproduce the behavior:

1. Click on "Open"
2. See: query param is well added, also with see a new history entry
3. do browser back
4. See: query param is well deleted
5. See: the state of the query param is not updated.

**Comment by gkielwasser** [comment]
> Thanks for the report, could you please try and enable the `windowHistorySupport` experimental flag and let me know if the error still occurs ?
> 
> Looks like 14.0.3 broke shallow routing entirely unless this flag is on, see #416 and a PR to track it #417.

Yes have the `windowHistorySupport ` enabled. I have also tested with `"next": "14.0.4-canary.28"`

It seems the same issue happen on this demo [Builder pattern](https://next-usequerystate.vercel.app/demos/builder-pattern?counter=2). But in this playground `windowHistorySupport ` seems not enabled.

**Comment by franky47** [comment]
If using the app router: try using `next@14.0.4-canary.37`, which fixes shallow routing.

If using the pages router, unfortunately the issue has been here for a while, and it being tracked in #419. I'm having a hard time making it work with all combinations of basePath and dynamic routes.

**Comment by franky47** [comment]
I merged #419 which includes a fix for `history: 'push'` on the pages router. It's available in `next-usequerystate@1.13.2-beta.1`. @gkielwasser can you please give it a try and let me know if it fixes your issue?

For the app router, updating Next.js to 14.0.4 is required to get the shallow routing fix (which impacts push).

**Comment by gkielwasser** [comment]
> I merged #419 which includes a fix for `history: 'push'` on the pages router. It's available in `next-usequerystate@1.13.2-beta.1`. @gkielwasser can you please give it a try and let me know if it fixes your issue?
> 
> For the app router, updating Next.js to 14.0.4 is required to get the shallow routing fix (which impacts push).

Yep good job, I confirm push is well sync now

**Comment by franky47** [comment]
Thanks for your feedback @gkielwasser, 1.13.2 has been released.
